# Generated by Django 2.2.5 on 2019-09-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('famil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='sabject',
            new_name='subject',
        ),
    ]
